### ISSUE TITLE
Pre-trained ImageNet model

### ISSUE THREAD

**Issue by xialeiliu** [cambridge-mlg/cnaps#11]
Do you have idea on how to learn a new pretrained ImageNet model using this framework by myself if I would like to try a different architecture?

**Comment by jfb54** [comment]
This is straightforward to do using PyTorch (though you could do something similar using TensorFlow). Below is the basic idea. 

1. Use the source code for one of the built-in PyTorch models from here: https://pytorch.org/docs/stable/torchvision/models.html. You will need to change the number of classes from 1000 to 712 (the number of classes in the MetaDataset training split). You could get model code from elsewhere as well.

2. Train the model with this code (or something similar): https://github.com/pytorch/examples/blob/master/imagenet/main.py. You will need to change the batch reading code to use the Meta-Dataset reader in batch mode (see the Batch Mode section on https://github.com/google-research/meta-dataset/blob/master/Intro_to_Metadataset.ipynb) to read standard training batches from the MetaDataset ILSVRC_2012 dataset.

3. Save out the trained model (but don't include the top level fully connected layer when you save it out).

Let me know if you need more detail.

**Comment by xialeiliu** [comment]
I see, I was worried that using code from other frameworks would have different preprocessing, which might be not good for further finetuning. As I understood, it would be good to use the same batch reading code as used in Meta_dataset code base.

**Comment by jfb54** [comment]
Yes, I recommend using the batch reading code from Meta-Dataset.

**Comment by xialeiliu** [comment]
Thanks!
