### ISSUE TITLE
Meta-Dataset version

### ISSUE THREAD

**Issue by xialeiliu** [cambridge-mlg/cnaps#12]
Could you clarify which meta-dataset version is used for this repo? Since Meta-dataset repo is updated very frequently.

**Comment by jfb54** [comment]
We try to keep up with the latest Meta-dataset version. We updated CNAPs to work with Meta-dataset version on 24 December 2020. Sorry, I don't have the precise Meta-dataset version number. Let us know if something doesn't work with the latest Meta-dataset and we'll fix anything promptly. We only use a small part of their code (the dataset reader). Next time we do an update, we will publish the precise version of Meta-dataset that we last tested with.

**Comment by xialeiliu** [comment]
I see. Thanks. I just updated a couple of lines in .gin file in order to be compatible with the latest meta-dataset version.
It worked.

**Comment by jfb54** [comment]
Thanks. Just curious, what lines did you need to change? We can then make the fix in the CNAPs code.

**Comment by xialeiliu** [comment]
I was trying something else, at some point, it was conplaining about _simclr_episode_fraction_, so I added two more lines:
EpisodeDescriptionConfig.ignore_hierarchy_probability = 0.0
EpisodeDescriptionConfig.simclr_episode_fraction = 0.0

but, when I rerun it again, it seems the code works perfectly fine.

It  was a bit confusing for the meta_dataset_config.gin, it seems that most variables are not used, is it true?

**Comment by jfb54** [comment]
Yes, most of the settings in meta_dataset_config.gin are over-ridden in the reader code. Agree, this is somewhat confusing.
