### ISSUE TITLE
from meta_dataset.data import *

### ISSUE THREAD

**Issue by liulu112601** [cambridge-mlg/cnaps#7]
Hi,
Thanks for the code!
one quick question:
https://github.com/cambridge-mlg/cnaps/blob/master/src/meta_dataset_reader.py#L8
from meta_dataset.data import dataset_spec as dataset_spec_lib

is the meta_dataset.data comes from the original meta-dataset github repo?

**Comment by jfb54** [comment]
Yes. We use the episode reader from the meta-dataset repository. Step 2 in our installation instructions says:

Configure Meta-Dataset:
- Follow the the "User instructions" in the Meta-Dataset repository (https://github.com/google-research/meta-dataset) for "Installation" and "Downloading and converting datasets". This will take some time.

Also, before you run CNAPs, you need to export the location of the meta-dataset source code (see Step 1 in our usage section):
```export META_DATASET_ROOT=<root directory of the cloned or downloaded Meta-Dataset repository>```
